table:
  name: v_meeting_clientSettings
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: meeting_clientSettings
  custom_root_fields: {}
select_permissions:
  - role: bbb_client
    permission:
      columns:
        - clientSettingsJson
      filter:
        meetingId:
          _eq: X-Hasura-MeetingId
    comment: ""
  - role: not_joined_bbb_client
    permission:
      columns:
        - clientSettingsJson
      filter:
        meetingId:
          _eq: X-Hasura-MeetingId
    comment: ""
